-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.client
(
    id integer NOT NULL DEFAULT nextval('client_id_seq'::regclass),
    phone bigint NOT NULL,
    password_number integer NOT NULL,
    password_series integer NOT NULL,
    first_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(30) COLLATE pg_catalog."default",
    family_status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT client_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.credit_agreement
(
    id integer NOT NULL DEFAULT nextval('credit_agreement_id_seq'::regclass),
    application_id integer NOT NULL,
    date_of_signing date NOT NULL,
    signature_status boolean NOT NULL,
    CONSTRAINT credit_agreement_pkey PRIMARY KEY (application_id)
);

CREATE TABLE IF NOT EXISTS public.credit_application
(
    id integer NOT NULL DEFAULT nextval('credit_application_id_seq'::regclass),
    client_id integer NOT NULL,
    amount_of_credit numeric NOT NULL,
    position_at_work character varying(40) COLLATE pg_catalog."default" NOT NULL,
    name_of_organization character varying(30) COLLATE pg_catalog."default" NOT NULL,
    period_of_employment_start date NOT NULL,
    period_of_employment_end date NOT NULL,
    CONSTRAINT credit_application_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.credit_decision
(
    id integer NOT NULL DEFAULT nextval('credit_decision_id_seq'::regclass),
    application_id integer NOT NULL,
    status boolean NOT NULL,
    credit_term integer NOT NULL,
    approved_credit_amount numeric NOT NULL,
    CONSTRAINT credit_decision_pkey PRIMARY KEY (application_id)
);

ALTER TABLE IF EXISTS public.credit_agreement
    ADD CONSTRAINT application_fk FOREIGN KEY (application_id)
    REFERENCES public.credit_application (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;
CREATE INDEX IF NOT EXISTS credit_agreement_pkey
    ON public.credit_agreement(application_id);


ALTER TABLE IF EXISTS public.credit_application
    ADD CONSTRAINT client_fkey FOREIGN KEY (client_id)
    REFERENCES public.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.credit_decision
    ADD CONSTRAINT application_fk FOREIGN KEY (application_id)
    REFERENCES public.credit_application (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;
CREATE INDEX IF NOT EXISTS credit_decision_pkey
    ON public.credit_decision(application_id);

END;